[build]
rustflags = ["-Z", "threads=8"]

[target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
# rustflags = ["-C", "target-feature=+crt-static"]


# [target.x86_64-unknown-linux-musl]
# linker = "x86_64-linux-musl-gcc"
