name: Rust

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
  
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      id: cache-rust
      uses: actions/cache/restore@v4
      with:
        path: |
          /home/runner/.cargo
          /home/runner/work/self-cloud/self-cloud/target
        key: self-cloud-cache

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    - run: rustup toolchain install nightly-2024-07-19
    - name: Add wasm32
      run: rustup target add wasm32-unknown-unknown

    - name: Install Cargo Leptos
      run: cargo install cargo-leptos

    # - name: Build
    #   run: cargo leptos build --release

    # - name: Compress site
    #   run: tar -cvf site-x64.tar target/site
    # - name: Rename x64 binary
    #   run: cp target/binrelease/server server-x64

    - name: Add aarch64
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Add aarch64 to Cargo.toml
      run: |
        mkdir .cargo
        echo "bin-target-triple = \"aarch64-unknown-linux-gnu\"" >> Cargo.toml
        echo "[target.aarch64-unknown-linux-gnu]" >> .cargo/config.toml
        echo "linker = \"gcc-aarch64-linux-gnu\"" >> .cargo/config.toml
        cat .cargo/config.toml

    - name: Build aarch64
      run: cargo leptos build --release

    - name: Compress site
      run: tar -cvf site-arm64.tar target/site
    - name: Rename arm64 binary
      run: cp target/aarch64-unknown-linux-gnu/binrelease/server server-arm64

    - name: Release
      run: |
          gh release delete nightly --yes || true
          git push origin :nightly || true

    - name: Upload to nightly
      run: |
          gh release create nightly --prerelease --title nightly --target $GITHUB_SHA \
            server-x64 \
            site-x64.tar \
            server-arm64 \
            site-arm64

    - name: Save cache
      id: cache-rust-save
      uses: actions/cache/save@v4
      with:
        path: |
          /home/runner/.cargo
          /home/runner/work/self-cloud/self-cloud/target
        key: self-cloud-cache
