name: Rust

on: 
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y clang cmake libevent-dev libclang-dev libcurl4-openssl-dev curl
    - run: rustup toolchain install nightly-2024-07-19
    - name: Add wasm32
      run: rustup target add wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v2

    - name: Install Cargo Leptos
      run: cargo install cargo-leptos

    - name: Build
      run: cargo leptos build --release


    - name: Install cross
      run: cargo install -f cross
    - name: Build arm64
      run: cross build --target aarch64-unknown-linux-gnu --package=server --bin=server --no-default-features --profile=binrelease

    - name: Compress site
      run: tar -cvf site.tar target/site

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            target/binrelease/server
            site.tar
